name: flutter_mvvm_template
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  hooks_riverpod: ^1.0.0
  flutter_hooks: ^0.18.0
  state_notifier: ^0.7.1
  freezed_annotation: ^1.0.0
  # Network
  dio: ^4.0.4
  retrofit: '>=3.0.0 <4.0.0'
  json_annotation: ^4.4.0
  # DB 
  shared_preferences: ^2.0.8
  # Component
  webview_flutter: ^3.0.0
  # Asset
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # Others
  device_preview: ^1.0.0
  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  freezed: ^1.0.0
  flutter_gen_runner: ^4.1.4
  retrofit_generator: '>=3.0.0 <4.0.0'
  json_serializable: ^6.0.1
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0

flutter:
  generate: true
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true